from backend.models.agent_dna import AgentDNA

AGENT_REGISTRY = [
    AgentDNA(
        id="autoresearch",
        name="AutoResearch Agent",
        tagline="5-agent autonomous research engine. Any topic, 90 seconds.",
        category="research",
        capabilities=["Deep web research", "Source citation", "Fact verification", "Contradiction detection", "Structured report generation"],
        tools_used=["Tavily Search", "Serper API", "FAISS Vector DB", "BeautifulSoup", "Groq LLaMA 3.3 70B"],
        avg_speed_seconds=90,
        accuracy_score=0.87,
        cost_per_run=0.00,
        agent_count=5,
        input_type="text query",
        output_type="structured markdown report with citations",
        total_runs=1247,
        star_rating=4.8,
        author="Team TechLions",
        version="1.0.0",
        status="live",
        intent_keywords=["research", "study", "investigate", "learn about", "explain", "analyze", "report on", "find information"]
    ),
    AgentDNA(
        id="competescope",
        name="CompeteScope Agent",
        tagline="Full competitor intelligence on any company in 60 seconds.",
        category="intelligence",
        capabilities=["Competitor mapping", "Pricing analysis", "Strengths & weaknesses", "Market positioning", "SWOT generation"],
        tools_used=["Tavily Search", "Groq LLaMA 3.3 70B", "LangChain"],
        avg_speed_seconds=60,
        accuracy_score=0.83,
        cost_per_run=0.00,
        agent_count=3,
        input_type="company name or product",
        output_type="competitor intelligence report",
        total_runs=389,
        star_rating=4.6,
        author="Team TechLions",
        version="0.9.0",
        status="live",
        intent_keywords=["competitor", "competition", "market", "rival", "compare", "vs", "alternative", "benchmark", "industry"]
    ),
    AgentDNA(
        id="codereview",
        name="CodeReview Agent",
        tagline="Paste a GitHub URL. Get a full code quality audit.",
        category="code",
        capabilities=["Bug detection", "Code quality scoring", "Security audit", "Refactor suggestions", "Complexity analysis"],
        tools_used=["GitHub API", "Groq LLaMA 3.3 70B", "AST Parser"],
        avg_speed_seconds=45,
        accuracy_score=0.91,
        cost_per_run=0.00,
        agent_count=2,
        input_type="GitHub repository URL",
        output_type="code audit report with line-level suggestions",
        total_runs=156,
        star_rating=4.7,
        author="Team TechLions",
        version="0.8.0",
        status="beta",
        intent_keywords=["code", "review", "github", "bug", "refactor", "audit", "quality", "security", "debug"]
    )
]
